version: '3.1'

services:
  app:
    container_name: api_backend
    environment:
      - TZ=America/Sao_Paulo
    build: .
    ports:
      - 3201:3201 #local:container
    volumes:
      - .:/home/node/app
      #- /home/node/app/node_modules #VOLUME ANONIMO - diretório que não será sobrescrito pela instrução acima
    depends_on:
      - db #nome do serviço que será dependente

  db:
    image: postgres:15.4
    container_name: api_db_postgres
    restart: always
    # volumes:
    #  - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: api
    ports:
      - 54320:5432 #local:container - no local costuma adicionar um 0 (zero) no final da porta para não conflitar com o banco local
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
